export default {
    "HomeMatic": "HomeMatic WebUI",
    "LANCOM": "Lancom Router",
    "HL-3142CW": "Brother HL-3142CW series",
    "Kerio Connect WebMail": "Kerio Connect WebMail",
    "NethServer": "NethServer",
    "loxone.com": "Loxone Webinterface",
    "Senec": "SENEC GmbH ist ein Energie-Unternehmen",
    "Brother MFC-J470DW": "Brother MFC-J470DW",
    "SolarLog": "SolarLog",
    "/sws/images/fav.ico": "SyncThru Webservice (Samsung)",
    "ShareCenter": "ShareCenter (default user:admin)",
    "Foscam": "Foscam IP Camera (default user:admin)",
    "DS1019plus": "Synology DS1019plus",
    "Nextcloud": "Nextcloud",
    "Smart-Heat-OS": "Smart-Heat-OS",
    "STIEBEL ELTRON": "STIEBEL ELTRON",
    "Varta Storage": "Varta Storage",
    "/view/viewer_index.shtml?id=": "Webcam?",
    "doc/page/login.asp": "Abus - ©Hikvision Digital Technology",
    "RESOL": "RESOL (admin:admin)",
    "/dlx/home": "RESOL? (admin:admin)",
    "nginx": "nginx default page",
    "Zarafa": "Zarafa WebAccess",
    "GIRA": "GIRA Product",
    "Hecstar db page": "Hecstar db page",
    "DS7700 WEB-Interface": "DS7700 WEB-Interface",
    "Vilar IPCamera Login": "Vilar IPCamera Login",
    "DVR Components Download": "DVR Components Download",
    "Brother MFC-J5320DW": "Brother MFC-J5320DW",
    "QNAP Turbo NAS": "QNAP Turbo NAS (admin:admin)",
    "403 Forbidden": "403 Forbidden",
    "503 Service Unavailable": "503 Service Unavailable",
    "Web Application Manager": "Web Application Manager",
    "Loxone Smart Home": "Loxone Smart Home (default user:admin password:admin)",
    "Loxone": "Loxone Product",
    "FRITZ!Box": "FRITZ!Box",
    "EHEIM": "EHEIM digital",
    "Minecraft Overviewer": "Minecraft Overviewer",
    "Synology": "Synology",
    "Axentra Server": "Axentra Server",
    "Please be patient as you are being re-directed to": "SonicWall Network Security Login",
    "SonicWALL": "SonicWALL",
    "Neige-Netzwerkkamera": "Schwenk-Neige-Netzwerkkamera",
    "Web Server Setup Guide": "Web Server Setup Guide",
    "LanMpegView0.htm": "Cam Guard",
    "aspx?gotodefault=true": "Windows Home Server?",
    "rpAuth.html": "Zyxel",
    "Bootloader-NET": "Anlage mit Bootloader-NET",
    "www.ta.co.at": "Anlage mit Bootloader-NET",
    "belkin": "Belkin Router",
    "pihole": "pihole",
    "TP-LINK": "TP-LINK Technologies",
    "DiskStation": "DiskStation",
    "RomPager": "RomPager Server",
    "mobotix": "Mobotix Webcam -",
    "Netzwerkkonfigurations-Assistent": "Windows Small Buisness Server",
    "TechniSat": "TechniSat Webserver(Receiver?)",
    "pressum": "Normale Homepage",
    "rcube_webmail": "Round Cube Webmail",
    "Vertriebsportal": "SAG Vertriebsportal",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz012345678": "Pragma Standard Login",
    "QNAP": "QNAP Web Server Settings",
    "Detachering": "Alko Detachering Webmail - Login",
    "mailscope": "mailscope",
    "FileVault": "iomega FileVault",
    "Redirecting to <a href=\"/cgi-bin/home": "TV Box Webinterface",
    "TeamViewer": "Running Teamviewer",
    "splashDefault-l-logo.jpg": "Blue Quartz Placeholder",
    "status.asp": "Acer Router",
    "IP300PTR": "IP Camera",
    "Hewlett-Packard Development": "Hewlett-Packard Development",
    "Willkommen": "Welcome Page",
    "Tobit": "Welcome Page",
    "Konfigurationsprogramm starten": "Telekom Router Speedport",
    "WG-602": "Handlink WG-602",
    "XAMPP": "XAMPP",
    "eMule": "eMule Webinterface",
    "server-ams": "server-ams",
    "Internetinformationsdienste": "Leere Seite",
    "Placeholder": "Placeholder Page",
    "window.location=\"cgi-bin/webmng.cgi?next_file=login.htm": "Peer TV Web -Management",
    "Enigma": "Enigma Webinterface (DBOX)",
    "yWeb": "yWeb (DBOX)",
    "IServ": "IServ Weboberflaeche",
    "BMR": "BMR Webserver",
    "MSNTV": "MSNTV",
    "Bosch": "Bosch 1ch DVR?",
    "IIS7": "IIS7 Internet Information Service",
    "IIS Windows Server": "IIS Windows Server",
    "WRT54G": "Linksys WRT54G",
    "Linksys_Blue.gif": "Linksys Storage System",
    "Connectivity": "Connectivity Server",
    "WL700gE": "WL700gE Configuration",
    "dmicros.com": "Dedicated Micros EcoSense",
    "LaserJet": "HP Laserjet Drucker",
    "Index of": "Index of (event. Dateien gefunden)",
    "Grandstream": "Grandstream Device Configuration",
    "Prestige": "Prestige Login",
    "ZyXEL": "ZyXEL ZyWALL Series",
    "Teledat": "Teledat Router",
    "Dreambox": "Dreambox Webcontrol",
    "works!": "Apache IT works Seite",
    "Joomla": "Joomla Seite",
    "www.a-link.com": "A-Link Login Screen",
    "Construction": "Under Construction",
    "GIPZ": "GIPZ Network System",
    "idesk": "idesk IServ",
    "IBM HTTP Server": "IBM HTTP Server",
    "Sunny WebBox": "Sunny WebBox, Standard PW->sma",
    "SMA Energy Meter": "SMA Energy Meter",
    "DVR MPEG4 ActiveX": "DVR MPEG4 ActiveX",
    "Funkwerk": "Funkwerk Gateway",
    "nst4TWN.exe": "DVR Viewer",
    "MattiSyno4x500": "Synology Cube Station - MattiSyno4x500",
    "tcpip.ssi": "RAINOTRONIK",
    "phpinfo": "phpinfo()",
    "window.location": "Weiterleitung ->",
    "location.href": "Weiterleitung -> location.href",
    "innovaphone": "innovaphone",
    "Document Moved": "Document Moved",
    "HTTP Error 404": "HTTP Error 404",
    "404 Not Found": "404 Not Found"
  };
